# Generated by Django 5.1.4 on 2025-02-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('contato', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('cep', models.CharField(max_length=10)),
            ],
        ),
    ]
