# Generated by Django 5.1.4 on 2025-02-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='qnt',
            field=models.IntegerField(default=0),
        ),
    ]
